[project]
name = "yunjispider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "attrs==25.3.0",
    "certifi==2025.8.3",
    "cffi==2.0.0",
    "charset-normalizer==3.4.3",
    "exceptiongroup==1.3.0",
    "greenlet==3.2.4",
    "h11==0.16.0",
    "idna==3.10",
    "markdown-it-py==4.0.0",
    "mdurl==0.1.2",
    "numpy==2.2.6",
    "outcome==1.3.0.post0",
    "pandas==2.3.2",
    "pillow==11.3.0",
    "pip>=25.2",
    "playwright==1.55.0",
    "pycparser==2.23",
    "pyee==13.0.0",
    "pygments==2.19.2",
    "pysocks==1.7.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "requests==2.32.5",
    "rich==14.1.0",
    "selenium==4.35.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "tabulate==0.9.0",
    "trio==0.30.0",
    "trio-websocket==0.12.2",
    "typing-extensions==4.14.1",
    "tzdata==2025.2",
    "urllib3==2.5.0",
    "websocket-client==1.8.0",
    "wsproto==1.2.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
